###
#-------------------------------------------------------------------------------
# Makefile
#-------------------------------------------------------------------------------
#
# Author:       Alwin Tareen
# Created:      Jul 04, 2020
# Compilation:  make plurality
#
# This Makefile compiles the plurality.c program.
#
##

plurality: plurality.c
	gcc -ggdb3 -O0 -std=c11 -Wall -Werror -Wextra -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wshadow -o plurality plurality.c

clean:
	rm -f *.o a.out core plurality log.txt

