###
#-------------------------------------------------------------------------------
# Makefile
#-------------------------------------------------------------------------------
#
# Author:       Alwin Tareen
# Created:      Jun 30, 2020
# Compilation:  make credit
#
# This Makefile compiles the credit.c program.
#
##

credit: credit.c
	gcc -ggdb3 -O0 -std=c11 -Wall -Werror -Wextra -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wshadow -o credit credit.c

clean:
	rm -f *.o a.out core credit log.txt

