# Generated by Django 3.2 on 2021-05-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210504_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='listings',
            field=models.ManyToManyField(blank=True, related_name='bid', to='auctions.Listing'),
        ),
    ]
