# Generated by Django 3.2 on 2021-05-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_bid_listings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='listings',
        ),
        migrations.AddField(
            model_name='listing',
            name='bids',
            field=models.ManyToManyField(blank=True, related_name='listings', to='auctions.Bid'),
        ),
    ]
