# Generated by Django 3.2 on 2021-05-08 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_listing_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='comment',
            new_name='comments',
        ),
    ]
